# Generated by Django 4.0.1 on 2022-01-10 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
