# Generated by Django 4.0.1 on 2022-01-10 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('examples', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocaleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),                
                ('content_id', models.PositiveIntegerField(blank=True, db_column='content_id', default=None, null=True)),
                ('code', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'locale_names',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='localename',
            index=models.Index(fields=['content_type', 'content_id'], name='locale_name_content_0a71c6_idx'),
        ),
    ]
