# Generated by Django 4.0.1 on 2022-01-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0004_localename_localename_locale_name_content_0a71c6_idx'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='localename',
            constraint=models.UniqueConstraint(fields=('content_type', 'content_id', 'code'), name='unique_locale_name'),
        ),
    ]
