# Generated by Django 4.0.1 on 2022-01-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0006_perk_perk_generic_perks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
