# Generated by Django 3.2.9 on 2021-12-05 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentable_type', models.ForeignKey(db_column='commentable_type', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('commentable_id', models.PositiveIntegerField(blank=True, db_column='commentable_id', default=None, null=True)),
                ('user', models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to=settings.AUTH_USER_MODEL)),                
                ('body', models.CharField(max_length=255, verbose_name='본문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['commentable_type', 'commentable_id', 'deleted_at'], name='comments_comment_ed5de0_idx'),
        ),
    ]
