# Generated by Django 4.0.1 on 2022-01-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.JSONField(default=None, null=True, verbose_name='계보'),
        ),
    ]
