# Generated by Django 4.0.1 on 2022-01-18 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField(blank=True, db_column='content_id', default=None, null=True)),
                ('content_type', models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('code', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'shop_names',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shops', to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(max_length=10, verbose_name='상점코드')),
                ('name', models.CharField(max_length=200, verbose_name='상점명')),
                ('order', models.IntegerField(default=99, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
            ],
            options={
                'db_table': 'shops',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='shopname',
            index=models.Index(fields=['content_type', 'content_id'], name='shop_names_content_f4551d_idx'),
        ),
        migrations.AddConstraint(
            model_name='shopname',
            constraint=models.UniqueConstraint(fields=('content_type', 'content_id', 'code'), name='unique_nameable'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['is_active', 'deleted_at'], name='shops_is_acti_170994_idx'),
        ),
    ]
