# Generated by Django 4.0.1 on 2022-01-14 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200, verbose_name='브랜드명')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active', 'deleted_at'], name='brands_is_acti_1cb39c_idx'),
        ),
    ]
