# Generated by Django 4.0.1 on 2022-01-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_products_code_5da1db_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('TEMP_STORAGE', '임시저장'), ('WAIT', '승인대기'), ('APPROVAL', '승인')], default='TEMP_STORAGE', max_length=12, verbose_name='승인 상태'),
        ),
    ]
