# Generated by Django 4.0.1 on 2022-01-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productapproval_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
