# Generated by Django 4.0.1 on 2022-01-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productapproval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productapproval',
            options={'managed': False},
        ),
    ]
