# Generated by Django 4.0.1 on 2022-01-18 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productapproval_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductApproval',
        ),
    ]
