# Generated by Django 4.0.1 on 2022-01-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productshopname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductShopName',
        ),
    ]
